### Classification Models

In [1]:
pwd

'C:\\Users\\HP\\Downloads\\Data Science'

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('C:/Users/HP/Downloads/Data Science/Classification data_Python.csv', header = 0)

In [4]:
df.head()

,price,resid_area,air_qual,room_num,age,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,Sold,avg_dist,airport_YES,waterbody_Lake,waterbody_Lake and River,waterbody_River
0,24.0,32.31,0.538,6.575,65.2,24.7,4.98,5.480,11.19200,23,0.049347,0,4.0875,1,0,0,1
1,21.6,37.07,0.469,6.421,78.9,22.2,9.14,7.332,12.17280,42,0.046146,1,4.9675,0,1,0,0
2,34.7,37.07,0.469,7.185,61.1,22.2,4.03,7.394,46.19856,38,0.045764,0,4.9675,0,0,0,0
3,33.4,32.18,0.458,6.998,45.8,21.3,2.94,9.268,11.26720,45,0.047151,0,6.0650,1,1,0,0
4,36.2,32.18,0.458,7.147,54.2,21.3,5.33,8.824,11.28960,55,0.039474,0,6.0625,0,1,0,0

### Logistic Regression

In [5]:
X = df[['price']]

In [6]:
y = df['Sold']

In [7]:
X.head()

   price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
clf_lr = LogisticRegression()

In [11]:
clf_lr.fit(X,y)

LogisticRegression()

In [12]:
clf_lr.coef_ #value of beta1

array([[-0.03571865]])

In [13]:
clf_lr.intercept_ #value of beta0

array([0.61477516])

Another method

In [14]:
import statsmodels.api as sn

In [15]:
X_cons = sn.add_constant(X)

In [16]:
X_cons.head()

   const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [17]:
import statsmodels.discrete.discrete_model as sm

In [18]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5

In [19]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Tue, 14 Apr 2026   Pseudo R-squ.:                 0.01788
Time:                        14:55:29   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

coef of const is beta0 and coef of price is beta1

### Logistic Regression with Multiple Predictors

In [20]:
X_multi = df.loc[:,df.columns != 'Sold']

In [21]:
X_multi.head()

,price,resid_area,air_qual,room_num,age,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,avg_dist,airport_YES,waterbody_Lake,waterbody_Lake and River,waterbody_River
0,24.0,32.31,0.538,6.575,65.2,24.7,4.98,5.480,11.19200,23,0.049347,4.0875,1,0,0,1
1,21.6,37.07,0.469,6.421,78.9,22.2,9.14,7.332,12.17280,42,0.046146,4.9675,0,1,0,0
2,34.7,37.07,0.469,7.185,61.1,22.2,4.03,7.394,46.19856,38,0.045764,4.9675,0,0,0,0
3,33.4,32.18,0.458,6.998,45.8,21.3,2.94,9.268,11.26720,45,0.047151,6.0650,1,1,0,0
4,36.2,32.18,0.458,7.147,54.2,21.3,5.33,8.824,11.28960,55,0.039474,6.0625,0,1,0,0

In [22]:
y_multi = df['Sold']

In [23]:
y_multi.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [24]:
clf_lrs_m = LogisticRegression()

In [25]:
clf_lrs_m.fit(X_multi,y_multi)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [26]:
clf_lrs_m.coef_ #value of beta1, beta2,...betan

array([[-0.24635378, -0.01729729, -0.11019231,  0.86258258, -0.00599853,
         0.22820224, -0.2102139 ,  0.18007077, -0.09087244, -0.00704845,
        -0.00499195, -0.32611321, -0.1052108 , -0.09487055, -0.01512317,
         0.20179835]])

In [27]:
clf_lrs_m.intercept_ #value of beta0

array([0.0167121])

In [28]:
import statsmodels.api as sn
import statsmodels.discrete.discrete_model as sm

In [29]:
X_cons_m = sn.add_constant(X_multi)

In [30]:
logit = sm.Logit(y_multi, X_cons_m).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6

In [31]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Tue, 14 Apr 2026   Pseudo R-squ.:                  0.1924
Time:                        14:55:30   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""